import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import { i18n } from '../../i18n-config';
import { nunito } from '../../utils/fontsImporter';

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export const metadata: Metadata = {
  title: 'SimpleCut',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, params }) {
  const paramss = await params;
  return (
    <html lang={paramss.lang}>
      <body style={{ background: 'black' }} className={nunito.className}>
        {children}
      </body>
    </html>
  );
}
