import type { Metadata } from 'next';
import { Gabarito, Nunito } from 'next/font/google';
import './globals.css';
import React from 'react';

const gabarito = Gabarito({
  subsets: ['latin'],
});

const nunito = Nunito({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'SimpleCut',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`nunito.className antialiased`}>{children}</body>
    </html>
  );
}
